#--------@/_config.yml--------------------------------------------------------->
title: Docs-Pub
email: annebrown@gmail.com
description: >- # Ignore newlines until "baseurl:"
  GitHub Pages, Jekyll SSG deployment of headless, framework agnostic Markdown CMS
remote_theme: olivier3lanc/Jekyll-LibDoc
url: "https://gh-pages.annebrown.ca"
github_username:  annebrown



# Default Ignored:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#--------@/_config.yml--------------------------------------------------------->
